### ISSUE TITLE
Error: More than one instance of bitcore-lib found.

### ISSUE THREAD

**Issue by danaki** [bijeebuss/icewallet#3]
Installed by instructions, got following error:
```
yuri@zerg ~/work/bitwallet » ./node_modules/.bin/iwpriv
/Users/yuri/work/bitwallet/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12
    throw new Error(message);
    ^

Error: More than one instance of bitcore-lib found. Please make sure to require bitcore-lib and check that submodules do not also include their own bitcore-lib dependency.
    at Object.bitcore.versionGuard (/Users/yuri/work/bitwallet/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:12:11)
    at Object.<anonymous> (/Users/yuri/work/bitwallet/node_modules/bitcore-mnemonic/node_modules/bitcore-lib/index.js:15:9)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/yuri/work/bitwallet/node_modules/bitcore-mnemonic/lib/mnemonic.js:3:15)
```

Of course the same applies if installed globally.

**Comment by bijeebuss** [comment]
ok i updated the package.json, try uninstalling and reinstalling again
